<?php
/*
LEGEND by (index)
0 - English
1 - Japanese
*/
$module_name = 'webinarandevents';

${$module_name.'_title'} = array(
	'webinarandevents',
	'ダッシュボード'
);
${$module_name.''} = array(
	'webinarandevents',
	'ダッシュボード'
);

${$module_name.'_manage_webinarandevents'} = array(
	'Manage Admin Exam',
	''
);

${$module_name.'_webinarandevent_details'} = array(
	'Admin Exam Details',
	''
);
${$module_name.'_webinarandevents_list'} = array(
	'Exam List',
	''
);
${$module_name.'_add_webinarandevent'} = array(
	'Add Admin Exam',
	''
);
${$module_name.'_add_webinarandevent_form'} = array(
	'Add Admin Exam Form',
	'チームフォームを追加'
);
${$module_name.'_edit_webinarandevent'} = array(
	'Edit Admin Exam',
	'チームを編集'
);
${$module_name.'_edit_webinarandevent_form'} = array(
	'Edit Ream Form',
	'チームフォームの編集'
);
${$module_name.'_update_webinarandevent'} = array(
	'Update Admin Exam',
	'チームを更新'
);
${$module_name.'_delete_webinarandevent'} = array(
	'Delete Admin Exam',
	'チームを削除'
);
${$module_name.'_restore_webinarandevent'} = array(
	'Restore Admin Exam',
	'チームを復元'
);
${$module_name.'_view_webinarandevent_details'} = array(
	'View Admin Exam Details',
	'チームの詳細を表示'
);

// FIELDS
${$module_name.'_applicantName'} = array(
	'Applicant Name',
	''
);
${$module_name.'_applicantName_placeholder'} = array(
	'Applicant Name',
	''
);

${$module_name.'_applicantCode'} = array(
	'Applicant Code',
	''
);
${$module_name.'_applicantCode_placeholder'} = array(
	'Applicant Code',
	''
);

${$module_name.'_examName'} = array(
	'Exam Name',
	''
);
${$module_name.'_examName_placeholder'} = array(
	'Exam Name',
	''
);
${$module_name.'_dateTake'} = array(
	'Date Start',
	''
);
${$module_name.'_dateTake_placeholder'} = array(
	'Date Start',
	''
);
${$module_name.'_dateStart'} = array(
	'Date & Time Start',
	''
);
${$module_name.'_dateEnd'} = array(
	'Date & Time Done',
	''
);

${$module_name.'_totalScore'} = array(
	'Total Score',
	''
);
${$module_name.'_totalScore_placeholder'} = array(
	'Total Score',
	''
);
${$module_name.'_totalPercent'} = array(
	'Percentage',
	''
);
${$module_name.'_totalPercent_placeholder'} = array(
	'Percentage',
	''
);
${$module_name.'_passingScore'} = array(
	'Passing Score',
	''
);
${$module_name.'_passingScore_placeholder'} = array(
	'Passing Score',
	''
);
${$module_name.'_statusScore'} = array(
	'Status',
	''
);
${$module_name.'_statusScore'} = array(
	'Status',
	''
);


























${$module_name.'_referrer_name'} = array(
	'Referrer Name',
	''
);
${$module_name.'_referrer_name_placeholder'} = array(
	'e.g. Web Integration, Payroll',
	''
);
${$module_name.'_newCode2'} = array(
	'New Code2',
	''
);
${$module_name.'_newCode2_placeholder'} = array(
	'New Code2',
	''
);
${$module_name.'_referrerID'} = array(
	'Referrer Number',
	''	
);
${$module_name.'_referrerID_placeholder'} = array(
	'e.g. Web Integration, Payroll',
	'例えば ウェブ統合、給与'
);

${$module_name.'_referrerEmail'} = array(
	'Referrer Email',
	''
);
${$module_name.'_referrerEmail_placeholder'} = array(
	'e.g. Web Integration, Payroll',
	''
);
${$module_name.'_codeGenerated'} = array(
	'Code Generated',
	''
);
${$module_name.'_codeGenerated_placeholder'} = array(
	'Code Generated',
	''
);

${$module_name.'_codeGenerated'} = array(
	'Code Generated',
	''
);
${$module_name.'_codeGenerated_placeholder'} = array(
	'Code Generated',
	''
);

${$module_name.'_codeUsed'} = array(
	'Code Used',
	''
);
${$module_name.'_codeUsed_placeholder'} = array(
	'Code Used',
	''
);

${$module_name.'_applicantEmail'} = array(
	'Applicant Email',
	''
);
${$module_name.'_applicantEmail_placeholder'} = array(
	'Applicant Email',
	''
);

${$module_name.'_timeGenerated'} = array(
	'Time Generated by Applicant',
	''
);
${$module_name.'_timeGenerated_placeholder'} = array(
	'Time Generated',
	''
);
${$module_name.'_dateGenerated'} = array(
	'Date Generated by Admin',
	''
);
${$module_name.'_dateGenerated_placeholder'} = array(
	'Date Generated',
	''
);
${$module_name.'_codegenereted_status'} = array(
	'Count Generated',
	''
);
${$module_name.'_codegenereted_status_placeholder'} = array(
	'Count Generated',
	''
);











${$module_name.'_department_id'} = array(
	'Department',
	'部門'
);

${$module_name.'_webinarandevent_id'} = array(
	'Admin Exam ID',
	'ユーザーID'
);
${$module_name.'_facebook_link'} = array(
	'Facebook Link',
	'Facebookリンク'
);
${$module_name.'_phone_number'} = array(
	'Phone Number',
	'電話番号'
);
${$module_name.'_position'} = array(
	'Position',
	'ポジション'
);
${$module_name.'_type_of_support'} = array(
	'Type Of Support',
	'サポートの種類'
);
${$module_name.'_referred_by'} = array(
	'Referred By',
	'参照元'
);
${$module_name.'_employee_ID'} = array(
	'Employee ID',
	'従業員ID'
);
${$module_name.'_referrer_email'} = array(
	'Referrer Email',
	'リファラーメール'
);

// MODALS
${$module_name.'_modal_delete_msg1'} = array(
	'Are you sure you want to delete this webinarandevent?',
	'このチームを削除してもよろしいですか？'
);
${$module_name.'_modal_delete_msg2'} = array(
	'Deleting this webinarandevent will remove it from the database permanently.',
	'このチームを削除すると、データベースから完全に削除されます。'
);

// FORM MESSAGES
${$module_name.'_code_required'} = array(
	'Admin Exam code is required.',
	'チームコードが必要です。'
);
${$module_name.'_code_exists'} = array(
	'Admin Exam code already exists. Please provide a unique webinarandevent code.',
	'チームコードは既に存在します。 一意のチームコードを入力してください。'
);
${$module_name.'_name_required'} = array(
	'Admin Exam name is required.',
	'チーム名が必要です。'
);
${$module_name.'_name_exists'} = array(
	'Admin Exam name already exists. Please provide a unique webinarandevent name.',
	'チーム名はすでに存在しています。 一意のチーム名を入力してください。'
);
${$module_name.'_department_required'} = array(
	'Please select a department.',
	'部門を選択してください。'
);

// NOTIFICATIONS
${$module_name.'_webinarandevent_add'} = array(
	'Admin Exam added!',
	'チームが追加されました！'
);
${$module_name.'_webinarandevent_edit'} = array(
	'Admin Exam updated!',
	'チームが更新されました！'
);
${$module_name.'_webinarandevent_restored'} = array(
	'Admin Exam restored.',
	'チームが復元されました。'
);
${$module_name.'_messages_webinarandevent_removed'} = array(
	'Admin Exam removed successfully.',
	'チームが正常に削除されました。'
);
${$module_name.'_messages_webinarandevent_deactivated'} = array(
	'This webinarandevent is deactivated. Contact your web administrator.',
	'このチームは無効になっています。 Web管理者に連絡してください。'
);
${$module_name.'_messages_webinarandevent_deleted'} = array(
	'This webinarandevent has been deleted.',
	'このチームは削除されました。'
);
${$module_name.'_webinarandevent_not_found'} = array(
	'Admin Exam not found!',
	'チームが見つかりません！'
);
${$module_name.'_restore_confirmation'} = array(
	'Are you sure you want to restore this webinarandevent?',
	'このチームを復元してもよろしいですか？'
);
?>